Attribute VB_Name = "basOcrConvert"
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'                                                           '
' basOcrConvert                                             '
'                                                           '
' (c) 2017-2025 Michael Brodsky, mbrodskiis@gmail.com       '
' (v) 20250225                                              '
'                                                           '
' All rights reserved. Unauthorized use prohibited.         '
'                                                           '
' DESCRIPTION                                               '
'                                                           '
' This module defines template for application-specific     '
' ocr engines and file conversion procedures                '
'                                                           '
' DEPENDENCIES                                              '
'                                                           '
' LibAIOOcr                                                 '
'                                                           '
' NOTES                                                     '
'                                                           '
' This version of the API has only been tested with         '
' MS OFFICE 365 (64-bit) implementations.                   '
'                                                           '
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Option Compare Binary
Option Explicit

'''''''''''''''''''''''
' Types and Constants '
'''''''''''''''''''''''

Public Const kOcrConvertErrFileToText = 11000   ' OCR output file error.
Public Const kOcrConvertErrFileConvert = 11001  ' Input file conversion error.

''''''''''''''''''''
' Public Interface '
''''''''''''''''''''

Public Function ocrConvert( _
    aOcrConvert As OcrParamsT _
) As String
    '
    ' Reads and returns ocr text generated from an input source file.
    '
    Dim fout As String
    
    ' Convert the source file to plain text.
    fout = ocrAppConvert(aOcrConvert)
    ' Read and return the OCR text.
    ocrConvert = NewFso().OpenTextFile(fout).readAll
    ' Cleanup any temp files we created.
    If fout <> aOcrConvert.FilePath Then Kill fout
    'End With
End Function

'''''''''''''''''''''
' Private Interface '
'''''''''''''''''''''

Private Function ocrAppConvert( _
    aOcrConvert As OcrParamsT _
) As String
    '
    ' Returns the output file generated by the OCR engine from
    ' the given input file in the temp folder.
    '
    ocrAppConvert = aOcrConvert.FilePath
End Function

